name: Sync to Public Profile Repo

on:
  push:
    branches: [ main ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push vers le dépôt public
        env:
          PAT: ${{ secrets.MY_GITHUB_PAT }}
        run: |
          git remote add public https://${PAT}@github.com/maxime-knv/survivor.git
          git push public HEAD:main --force